# Same base image/digest as ./Dockerfile.
# NOTE that this - in real-life - would be a private Docker image
FROM cgr.dev/chainguard/wolfi-base:latest@sha256:96ff486b326d15db16aa1fbd41a17043a557bebf76d2c0ac932e717534025940

# NOTE that this would likely already be wired up to use our private packages
RUN apk add --no-cache internal-tool=1.4.2-r0
