# Same base image/digest as ./Dockerfile.
# NOTE that this - in real-life - would be a private Docker image
FROM cgr.dev/chainguard/wolfi-base:latest@sha256:1d95114038f76513a9ace6fca107d5582b08c65981f81f61cb56bf7fd2ef216d

# NOTE that this would likely already be wired up to use our private packages
RUN apk add --no-cache internal-tool=1.4.2-r0
